version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - ./data/:/var/lib/rabbitmq
        - ./log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: tpa
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - matching-interface@internal
networks:
  matching-interface@internal:
    name: matching-interface@internal
    external: true